# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c76faecf4cb42a7d4b574ba32499ff788a5c3cc99a9a25c02346bc8032ded4ad2e82bd16233e0af43079da6f6a131ac8e672dd1be571ec5b248aff4b9d11283

test:
  secret_key_base: 9ae0896948d2de7aed3b561a9758584c011bd73aafc3b3c591e36470284a67986e10c4e15400dfcc39f12f9d3a1f9ddecfd4fdb348abd7a8ae7e796d18e69f19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
